---
title: "Vyučované kurzy"
output: html_document
---

V současné době vyučujeme následující kurzy:

**Úvod do analýzy dat v R (SIS kód: ASGV00154)**

Kurz je úvodem do programovacího jazyka R vyvinutého pro statistickou analýzu dat. V kurzu není předpokládána předchozí znalost jazyka R, ale podmínkou je základní znalost statistiky a výhodou jsou předchozí zkušenosti s analýzou dat. [Stránky Úvodu do analýzy dat jsou dostupné zde](https://sociology-fa-cu.github.io/Uvod_do_analyzy_dat_v_R/index.html).

**Aplikovaná regrese v R (SIS kód: ASGV00995)**

Kurz seznámí studenty s metodou lineární regresní analýzy s důrazem na aplikované využití v softwaru R. Design kurzu se zaměřuje na studenty společenskovědních oborů, což se projevuje v jeho zacílení na koncepční pochopení lineární regrese a praktické aplikace ve společenských vědách. [Stránky Aplikované regrese v R jsou dostupné zde](https://sociology-fa-cu.github.io/appliedregressioninr/).

**Vybraná témata analýzy dat (SIS kód: ASGV00993)**

Tento předmět je zamýšlen jako příležitost pro studenty doktorského a magisterského studia ke zvládnutí pokročilých nebo inovativních metod analýzy dat. Celkové množství přímé výuky je menší než při klasické výuce. Větší prostor je naopak věnován samostatné přípravě na jednotlivá témata. [Stránky Vybraných témat analýzy dat jsou dostupné zde](https://sociology-fa-cu.github.io/vybranatemataanalyzy/).


**Statistika 1 (SIS kód: ASG100117)**

Kurz Statistika 1 není součástí tohoto klastru, jde o povinný předmět bakalářského programu na Katedře sociologie FF UK, nicméně [webová opora pro výuku kurzu Statitika 1](https://sociology-fa-cu.github.io/statistika1/) je vytvořena v podobném duchu jako pro kurzy výše.  