---
output: html_document
---

<br>

Na této stránce nabízíme seznam zdrojů vhodných pro samostudium témat, se kterými se v praxi často setkají kvantitativně orientovaní výzkumníci v sociálních vědách. Vybrané zdroje jsou zaměřeny primárně pro studenty a začínající výzkumníky.

:::  {.panel-tabset}

## Základy matematiky

<br> Přestože dnes výzkumníci mohou velkou část svých výpočtů abstrahovat díky specializovanému softwaru, vyplatí se i tak mít alespoň konceptuální znalost matematiky, na kterých běžné statistické modely stojí. A to zejména v oblastech lineární algebry a kalkulu.

### Učebnice

<br> **A Mathematics Course for Political and Social Research (W. Moore & D. Siegel, 2013)**

Obsáhlá a zároveň stravitelná učebnice, která čtenáře provede všemi důležitými aspekty matematiky. Napsaná se zaměřením na sociální vědce, každá kapitola knihy obsahuje intuitivní uvedení tématu, detailní popis a praktický příklad. Kniha je dostupná v knihovně Fakulty sociálních věd UK.

**Essential Mathematics for Political and Social Research (J. Gill, 2006)**

Kratší učebnice zaměřená na konceptuální výklad pojmů nezbytných pro pochopení vnitřního fungování statistických modelů. Každá kapitola obsahuje praktický příklad ušitý na míru politologům a sociologům, který osvětluje, jak je daný koncept využíván v praxi. Kniha je dostupná v knihovně Fakulty sociálních věd UK.

**Linear Algebra: Step by Step (K. Singh, 2014)**

Učebnice zaměřená srozumitelný výklad lineární algebry, která je mimo jiné základním pilířem všech lineárních modelů. Kniha přináší jednoduše pochopitelný výklad, který nepředpokládá žádné předchozí zkušenosti s matematikou. Elektronická verze učebnice je pro studenty Univerzity Karlovy dostupná v rámci kolekce *eBook Academic Collection*, přístupná skrze vyhledávač [Ukaž](https://cuni.primo.exlibrisgroup.com/discovery/search?vid=420CKIS_INST:UKAZ&lang=cs).

### Videa

<br> **Essence of Linear Algebra (3blue1brown)**

Série krátkých videí zaměřených představení lineární algebry. Místo matematických vzorců jsou videa zaměřená na vizuální a intuitivní pochopení matematiky. Jsou proto vhodná jako jemné uvedení do tématu před tím, než se studenti ponoří do detailnějších počtů. Videa jsou k dispozici na [Youtube](https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab).

**Essence of Calculus (3blue1brown)**

Série navazující na *Essence of Linear Algebra*. Stejné jako ta předchozí, i tato série videí klade velký důraz na intuitivní pochopení problematiky pomocí vizualizací. Videa jsou k dispozici na [Youtube](https://www.youtube.com/watch?v=WUvTyaaNkzM&list=PL0-GT3co4r2wlh6UHTUeQsrf3mlS2lk6x).

## Statistika a pravděpodobnost

<br> Teorie pravděpodobnosti, a na ní stojící statistika, představuje denní chléb každého kvantitativního sociologa. Od jednoduchých deskriptivních statistik po komplikované nelineární modely, aplikaci statistiky najdeme ve většině kvantitativně orientovaných sociologických článků. Její znalost jde proto jen stěží přecenit a jejímu studiu se vyplatí věnovat dostatek času.

Jeden z garantů klastru Kvantitativních metod analýzy dat vyučuje na Katedře sociologie také úvodní kurz Statistiky. [Dedikované a věčně rozpracované stránky kurzu Statistika 1 jsou dostupné zde.](https://sociology-fa-cu.github.io/statistika1/)

#### Učebnice

<br> **Introduction to Probability (J. Blitzstein & J. Hwang, 2019)**

Učebnice srozumitelně pokrývající základy teorie pravděpodobnosti, od definice pravděpodobnosti po distribuční funkce. Prvních šest kapitol pokrývá většinu témat, se kterými se studenti setkají během studia na katedrách sociologie a psychologie. Zájemci ovšem mohou pokračovat ve studiu zbytku knihy, a to zejména kapitol o conditional expectations (důležitý pojem pro pochopení regresních modelů) a o Markovových řetězcích (které hrají důležitou roli v bayesiánských modelech). Učebnice je dostupná v knihovně Fakulty sociálních věd Uk, případně elektronicky v rámci kolekce ProQuest Ebook Central skrze [Ukaž](https://cuni.primo.exlibrisgroup.com/discovery/search?vid=420CKIS_INST:UKAZ&lang=cs).

**Learning Statistics with R: A tutorial for psychology students and other beginners (D. Navarro, 2018)**

Volně šiřitelná učebnice statistické inference, která pokrývá všechna témata, se kterými se běžně setkají studenti psychologie, sociologie a příbuzných oborů. Kniha je zaměřená primárně na frekventistickou inferenci a testování nulových hypotéz, obsahuje ale také kapitoly zaměřené na deskriptivní analýzu a bayesiánskou statistiku. Učebnice je zdarma dostupná na [Open Textbook Library](https://open.umn.edu/opentextbooks/textbooks/559) a existuji pro ni R balíček [lst](https://github.com/svannoy/lsr-package).

**Statistical Rethinking: a Bayesian Course with Examples in R and Stan (R. McElreath, 2016)**

Učebnice zaměřená na takzvaný bayesiánský přístup ke statistice, který představuje čím dál více populární alternativu k frekventistické inferenci. Tato kniha je známá (a populární) mimo jiné svou atypickou strukturou, která může být atraktivní pro čtenáře znuděné klasickými učebnicemi. Učebnice je dostupná v knihovně Filozofické fakulty UK a využívá svůj vlastní R balíček, zvaný [rethinking](https://github.com/rmcelreath/rethinking).

**Doing Bayesian Data Analysis: A Tutorial with R, Jags, and Stan (J. Krushke, 2015)**

Učebnice bayesiánské statistiky s klasičtější strukturou, než je výše zmíněná *Statistical Rethinking*. Stejně jako ta předchozí, tato kniha přináší přátelský úvod do bayesiánské inference, včetně implementace v několika programovacích jazycích. Kniha je dostupná v knihovně Filozofické fakulty Uk.

**Regression and Other Stories (A. Gelman, J. Hill & A. Vehtari, 2021)**

Učebnice zaměřená na uvedení čtenáře do teorie a praxe lineárních regresních modelů. Kniha se zaměřuje primárně na konceptuální výklad témat, spíše než matematickou teorii, a obsahuje řadu praktických příkladů. Výklad vychází primárně z bayesiánské statistiky, většina kapitol je ale stejně relevantní i pro příznivce frekventistického přístupu. Učebnice je dostupná v knihovně Filozofické fakulty UK.

**Applied Regression Analysis and Generalized Linear Models (J. Fox, 2016)**

Matematicky rigoróznější uvedení do tématu regresních modelů, které pokrývá vše od jednoduché lineární regrese, až po zobecnělé lineární modely. Učebnice obsahuje řadu praktických příkladů v R. Kniha je dostupná v knihovně Vysoké školy ekonomické.

**Data Analysis Using Regression and Multilevel/Hierarchical Models (A. Gelman & J. Hill, 2006)**

Tato kniha je dnes již klasickým zdrojem pro studium víceúrovňových modelů. Učebnice je psaná srozumitelným jazykem a obsahuje řadu praktických rad a příkladů. Nevýhodou je zastaralý kód. Autoři přistupují k problematice z bayesiánské perspektivy, většina obsahu je ale platná také pro frekventistický přístup. Kniha je dostupná v knihovně Filozofické fakulty UK.

**Multilevel Analysis: An Introduction To Basic And Advanced Multilevel Modeling (T. Snijder, 2012)**

Detailnější učebnice víceúrovňových modelů, která dává větší prostor matematickým vzorcům. Přesto představuje praktické uvedení do tématu, a to včetně složitějších modelů. Kniha je dostupná v knihovně Pedagogické fakulty UK.

### Články

<br> **To Explain or To Predict? (G. Shmueli, 2010)**

Článek vysvětlující rozdíly mezi analýzami zaměřenými na predikci a těmi zaměřenými na testování hypotéz, a proč je k nim třeba přistup rozdílně. Článek je dostupný [zde](https://www.stat.berkeley.edu/~aldous/157/Papers/shmueli.pdf).

**The ASA Statement on p-Values: Context, Process, and Purpose (R. Wasserstein & N. Lazar, 2016)**

Článek Americké statistické asociace stručně objasňující podstatu p hodnot a jejich roli ve výzkumu. Článek je dostupný [zde](https://amstat.tandfonline.com/doi/pdf/10.1080/00031305.2016.1154108).

**Statistical tests, P values, confidence intervals, and power: a guide to misinterpretations (S. Greenland & et., 2016)**

Doplněk k výše zmíněnému prohlášení Americké statistické asociace, obsahující výčet nejčastějších chyb vyskytujících se při použití statistických testů. Text je dostupný [zde](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4877414/).

**Bad statistical practice in pharmacology (and other basic biomedical disciplines): you probably don't know P (M. Lew, 2012)**

Přestože si to dnes jen málo výzkumníků uvědomuje, způsobů jak interpretovat p hodnoty je více než jeden. Tento Článek osvětlující dva základní přístupy aplikace statistických testů, a to Fisherův přístup na jedné straně a Neyman-Pearsonův přístup na straně druhé. Text je užitečný zejména pro ty, kdo si chtějí udělat jasno, jak s p hodnotami pracovat. Dostupné [zde](https://bpspubs.onlinelibrary.wiley.com/doi/10.1111/j.1476-5381.2012.01931.x).

**Analyzing ordinal data with metric models: What could possibly go wrong? (T. Lidell & J. Kruschke, 2018)**

Článek popisující úskalí modelování ordinálních dat jako metrických (kardinálních) a jeho alternativy.

**Alternatives to randomisation in the evaluation of public-health interventions: statistical analysis and causal inference (S. Cousen et al., 2011)**

Krátký přehled možností kauzální inference bez nutnosti využívat klasický experimentální design.

## Psychometrie

<br> Sociální vědci se často zabývají studiem jevů, které nelze pozorovat přímo, jako jsou například postoje, hodnotové orientace nebo kognitivní schopnosti. Problematikou měření nepozorovatelných, takzvaně latentních, proměnných se zabývá vědní obor zvaný psychometrie. Základy této psychometrie by měl ovládat každý kvantitativně orientovaný sociolog.

### Učebnice

<br> **Psychometrika: Měření v psychologii (T. Urbánek, D. Denglerová & J. Širúček, 2011)**

Krátká učebnice uvádějící čtenáře do oboru psychometrie. Obsahuje výčet základních pojmů, a dále přehled a srovnání nejvýznamnějších psychometrických teorií. Vhodná zejména pro začínající studenty. Kniha je dostupná v knihovně Filozofické fakulty Uk a studenti Filozofické fakulty si také mohou stáhnout elektronickou verzi v rámci služby EBSCOhost eBooks skrze prohlížeč [Ukaž](https://cuni.primo.exlibrisgroup.com/discovery/search?vid=420CKIS_INST:UKAZ&lang=cs).

**Measurement Theory and Applications for the Social Sciences (D. Banadlos, 2018)**

Obsáhlejší učebnice obsahující výklad nejpopulárnějších teorií měření, včetně klasické testové teorie, teorie odpovědi na položku a teorie latentních tříd. Kniha také obsahuje obecné rady vytváření dotazníků, formulaci otázek a podobně. Učebnice je dostupná v knihovně Filozofické fakulty Uk a pro studenty fakulty je také dostupná v elektronické verzi v rámci kolekce ProQuest Ebook Central skrze vyhledávač [Ukaž](https://cuni.primo.exlibrisgroup.com/discovery/search?vid=420CKIS_INST:UKAZ&lang=cs).

#### Články

<br> **On the Use, the Misuse, and the Very Limited Usefulness of Cronbach's Alpha (Sijtsma, 2009)**

Článek upozorňující na praktické problémy spojené s používáním Cronbachova alfa, v současné době nejpopulárnějšího indexu reliability. Text popisuje předpoklady alfa koeficientu, důsledky jejich porušení a alternativní řešení. Článek je zdarma dostupný [zde](https://link.springer.com/article/10.1007%2Fs11336-008-9101-0).

**Comparison of Classical Test Theory and Item Response Theory in Individual Change Assessment (R. Jabrayilov, W. Emons, K. Sijtsma, 2016)**

Článek popisující aplikaci dvou nejpopulárnějších psychometrických teorií, klasické testové teorie a teorie odpovědi na položku, v aplikovaném výzkumu.

**Evaluating the use of exploratory factor analysis in psychological research (L. Fabrigar et al., 1990)**

Text obsahující praktické rady pro aplikaci explorační faktorové analýzy, jednoho ze stavebních kamenů klasické testové teorie.

## Programování

<br> Kvantitativní analýza dat v dnešní době vyžaduje rostoucí míru znalosti programování. To není dáno pouze zvyšující se komplexitou analýz samotných, ale také rostoucím důrazem na reprodukovatelný výzkum a automatizovaný reporting. Přestože programovacích jazyků dnes existují stovky, pro analýzy dat většina výzkumníků využívá jazyk R, Python nebo Julia.

#### Učebnice

<br> **R for Data Science (H. Wickham & G. Grolemund, 2017)**

Kniha pro úplné začátečníky, uvádějící své čtenáře do programovacího jazyka R, který je v dnešní době v sociálních vědách pravděpodobně nejrozšířenější. Kniha je založená na takzvaném [Tidyverse](https://www.tidyverse.org/), souborů balíků populárních pro svou uživatelskou přívětivost a gramatickou konzistenci. Čtenáři se dozví vše od instalace R, přes čištění dat, až po jejich vizualizaci. Kniha je zdarma dostupná [zde](https://r4ds.had.co.nz/index.html).

**ggplot2: elegant graphics for data analysis (H. Wickham, D. Navarro & T. Pedersen)**

Kniha detailně popisující balíček ggplot2, jeden z nejpopulárnější R balíčků pro vizualizaci. Text je vhodný zejména pro čtenáře, kteří už znají základy práce s R a chtějí se zlepšit ve vytváření komplexnějších grafů. Kniha je zdarma dostupná [zde](https://ggplot2-book.org/).

**R Markdown Cookbook (Yihui Xie, C. Dervieux & E Riederer, 2021)**

Učebnice R balíčku Rmarkdown, umožňující psaní a export textových reportů přimo v R. Čtenáři se naučí kombinovat datovou analýzu a text pro vytváření článků, knih, reportů, prezentací i webových stránek. Kniha je zdarma dostupná [zde](https://bookdown.org/yihui/rmarkdown-cookbook/).

**Advanced R (H. Wickham, 2019)**

Kniha detailněji popisující fungovování jazyka R jako takového. Vhodná zejména pro čtenáře se zájmem o programování a vývoj vlastních aplikací či balíků. Kniha je zdarma dostupná [zde](https://adv-r.hadley.nz/).

**Reproducible Research with R and RStudio (C. Gandrud, 2020)**

Prakticky orientovaná kniha popisující dobrou praxi organizace analytických projektů pro zajištění přehlednosti a reprodukovatelnosti. Kniha obsahuje tipy pro organizaci složek, využívání Rmarkdownu pro reprodukovatelné analýzy a zálohování dat pomoci programu git a stránky Github. Kniha je dostupná v knihovně Filozofické fakulty UK.

### Užitečné R balíky

<br> **rstanarm** - balíček pro výpočet základních bayesiánských modelů. Vhodný pro začátečníky, jelikož ve svých výstupech obsahuje řadu rad pro interpretaci. [Stránky balíčku](https://mc-stan.org/rstanarm/).

**brms** - balíček pro pokročilejší bayesiánské modely. Flexibelnější, ale možná méně přívětivější pro začátečníky, než rstanarm. [Stránky balíčku](https://www.rdocumentation.org/packages/brms/versions/2.16.3).

**lme4** - pravděpodobně nejpopulárnější balíček pro výpočet víceúrovňových/hierarchických modelů. [Github stránky balíčku](https://github.com/lme4/lme4/)

**DHARMa** - balíček pro diagnostiku víceúrovňových/hierarchických a dalších komplikovaných modelů pomocí randomizovaných kvantilových reziduí. Doporučují projít [článek](https://mran.revolutionanalytics.com/web/packages/DHARMa/vignettes/DHARMa.html) autora.

**ordinal** - balíček pro výpočet ordinální logistické regrese, užitečný zejména pro výzkumníky, kteří často pracují s likertovskými položkami. [Github stránky balíčku](https://rdrr.io/cran/ordinal/man/ordinal-package.html)

**psych** - balíček obsahující řadu psychometrických funkcí, jako výpočet koeficientů reliability nebo výpočet faktorové analýzy či modelů teorie odpovědi na položku. [Manuál balíčku](http://personality-project.org/r/overview.pdf).

**lavaan** - balíček pro výpočet modelů strukturálních rovnic (SEM), včetně faktorové analýzy. [Stránky balíčku](https://www.lavaan.ugent.be/).

**blavaan** - bayesiánská obdoba balíčku lavaan. [Stránky balíčku](https://ecmerkle.github.io/blavaan/).

**mirt** - balíček pro výpočet modelů založených na teorii odpovědi na položku, včetně komplikovanějších typů modelů. [Stránky balíčku](https://www.rdocumentation.org/packages/mirt/versions/1.35.1).

**ggeffects** - balíček pro vizualizaci regresních modelů, pro zjednodušení jejich interpretace. S výslednými grafy je možné pracovat jako s ostatními grafy vytvořenými pomocí balíčku ggplot2. [Stránky balíčku](https://strengejacke.github.io/ggeffects/).

**margins** - balíček pro výpočet marginálních efektů a vizualizaci regresních modelů. Obsahuje některé pokročilejší funkce oproti balíčku ggeffects. [Stránky balíčku](https://www.rdocumentation.org/packages/margins/versions/0.3.26).

:::