---
output:
  html_document:
    css: "css/site-style.css"
---

</br>

Metodologické přednášky našich členů mimo vyučované kurzy, například jednorázové přednášky, veřejná vystoupení atp.

## 2021/2022

<details><summary>Datová gramotnost - Jaromír Mazák (22. března 2022)</summary>

- Vyučující: Mgr. Jaromír Mazák, Ph.D. [(Více o lektorovi zde)](https://ksoc.ff.cuni.cz/mazak/)
- Termín: 22. března 2022 od 10:00 do 11:30 
- Formát: Online, 90 minut

Na odkaze níže naleznete kompletní prezentaci k semináři. Při práci s HTML verzí prezentací je možné využívat následujících klávesových zkratek:

- šipkami je možné přecházet z jednoho snímku na druhý.
- klávesa `f` spustí zobrazení plné obrazovky (fullscreen)
- klávesa `w` spustí širokoúhlé zobrazení (widescreen)
- klávesa `o` zobrazí přehled snímků
- klávesa `p` zobrazí poznámku k aktuálnímu snímku (pokud existuje)

[Prezentace ke spuštění v prohlížeči](slides/data_literacy.html)


**Anotace**

V ideálním světě by data měla vést k přesnější představě o realitě a k lepším rozhodnutím. Pro vědce jsou navíc základní surovinou pro vytváření vědění. Nedávná replikační krize v psychologii i jiných oborech nicméně ukázala, že ani vědecká komunita není imunní proti nesprávné práci s daty. Mladí vědci tak stojí před výzvou, aby vedle zájmu o svůj obor věnovali kritickou pozornost také zaběhnutým či oborovým postupům práce s daty a posouvali svůj obor nejen ve věcné rovině, ale také metodologicky.Tento 90minutový seminář je koncipován jako pozvánka do světa práce s daty, která není jen mechanická či „podle kuchařky“, nýbrž je citlivá k různými omezením, která s prací s daty nutně souvisí, a nečiní závěry, pro které v datech není opora. Cílem semináře je doktorandům pomoct v osvojení si návyků, díky kterým dokážou při práci s daty ve správnou chvíli zpozornět a klást si důležité otázky. Konkrétně bude věnována pozornost vybraným nástrahám popisné statistiky, problematice kauzální inference a kontroverzi kolem p-hodnoty včetně vysvětlení replikační krize. Účastníkům budou doporučeny prameny pro návazné studium. Předpokládá se, že účastníci již například v průběhu bakalářského nebo magisterského studia absolvovali základní statistické a metodologické kurzy a mají alespoň základní pochopení lineární regrese, testování nulových hypotéz a mají zkušenost s interpretací výstupů softwaru pro statistickou analýzu (např. tabulky regresních koeficientů, standardních chyb a p-hodnot).

[Odkaz na kurz na webu doktorského studia Univerzity Karlovy](https://phd.cuni.cz/PHD-239.html?event=23494&lang=cz)

</details>

<details><summary>Principy a praxe vizualizace dat - Jaromír Mazák (TBA)</summary>

TBD

</details>

<br>

## 2020/2021

- TBD